export const ActionTypes = {
	USER: {
		SET_LOGIN: "SET_LOGIN",
		UPDATE_USER: "UPDATE_USER",
		LOGOUT: "LOGOUT",
	},
	EVENT: {
		CREATE_EVENT: "CREATE_EVENT",
		ALL_EVENTS: "ALL_EVENTS",
		UPDATE_EVENT: "UPDATE_EVENT",
		REMOVE_EVENT: "REMOVE_EVENT",
		SET_CREATED: "SET_CREATED",
		SET_INTERESTED: "SET_INTERESTED",
		SET_REGISTERED: "SET_REGISTERED",
		UPDATE_INTERESTED: "UPDATE_INTERESTED",
		UPDATE_REGISTERED: "UPDATE_REGISTERED",
	},
};
